name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-flake:
    name: Check Flake
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            accept-flake-config = true
            experimental-features = nix-command flakes

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Check flake
        run: nix flake check --all-systems --show-trace

  # build-darwin:
  #   name: Build Darwin Configuration
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install Nix
  #       uses: DeterminateSystems/nix-installer-action@v14
  #       with:
  #         extra-conf: |
  #           accept-flake-config = true

  #     - name: Setup Magic Nix Cache
  #       uses: DeterminateSystems/magic-nix-cache-action@v8

  #     - name: Build Darwin configuration
  #       run: |
  #         nix build .#darwinConfigurations.Jan-Philips-MacBook-Pro.system \
  #           --show-trace \
  #           --print-build-logs

  # build-nixos:
  #   name: Build NixOS Configuration
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install Nix
  #       uses: DeterminateSystems/nix-installer-action@v14
  #       with:
  #         extra-conf: |
  #           accept-flake-config = true

  #     - name: Setup Magic Nix Cache
  #       uses: DeterminateSystems/magic-nix-cache-action@v8

  #     - name: Setup QEMU for aarch64
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y qemu-user-static

  #     - name: Build NixOS configuration (Pi)
  #       run: |
  #         nix build .#nixosConfigurations.pi.config.system.build.toplevel \
  #           --system aarch64-linux \
  #           --show-trace \
  #           --print-build-logs

  check-formatting:
    name: Check Formatting
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            accept-flake-config = true
            experimental-features = nix-command flakes

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Check formatting with treefmt
        run: devenv shell treefmt --fail-on-change
